# Use official OpenJDK image
FROM openjdk:17-jdk-slim

# Set working directory
WORKDIR /backend1

# Copy JAR file to container
COPY backend-0.0.1-SNAPSHOT.jar app.jar

# Expose the application port
EXPOSE 8080

# Run the application
CMD ["java", "-jar", "app.jar"]
